The Many Faces of the Single Responsibility Principle v1.0
d-r-q/developing-ergonomic-code pull request #5
Opened 2021-09-19 22:48 UTC by shamisem

2021-09-22 23:21 UTC, d-r-q requested changes

2021-09-22 23:21 UTC, d-r-q commented on azhidkov.pro/content/posts/21/06/210626-srp-interpretations.en.adoc
> +Martin keeps explaining the basic idea of SRP as separating the code based on its responsibilitiesZZ in his https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882[Clean Code]
```suggestion
Martin keeps explaining the basic idea of SRP as separating the code based on its responsibilities in his https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882[Clean Code]:
```

2021-09-22 23:21 UTC, d-r-q commented on azhidkov.pro/content/posts/21/06/210626-srp-interpretations.en.adoc
> +Here, he's talking about separating code by *people behind writing it*.
Кажется, вы тут перевели как разделение по авторам кода, а вообще речь о разделении по конечным пользователям кода.
При том это могут быть разного рода пользователи:
1) в первую очередь пользователи/заказчики
2) эксплуатационная команда и тестеры
3) строго говоря сами девелоперы тоже есть:)

2021-09-22 23:21 UTC, d-r-q commented on azhidkov.pro/content/posts/21/06/210626-srp-interpretations.en.adoc
> +You should separate the "default library" (the domain) and the "scripts" (functions) of the application.
```suggestion
You should separate the "standard library" (the domain) and the "scripts" (functions) of the application.
```

2021-09-22 23:21 UTC, d-r-q commented on azhidkov.pro/content/posts/21/06/210626-srp-interpretations.en.adoc
> +interactors and Evans in his DDD as the separation of application and domain services.
```suggestion
This is dicussed by both Martin in his Clean Architecture as the separation of interactors and
entities and Evans in his DDD as the separation of application and domain services.
```
Это уже в оригинале небольшой косяк

2021-09-22 23:21 UTC, d-r-q commented on azhidkov.pro/content/posts/21/06/210626-srp-interpretations.en.adoc
> +image::/posts/21/06/images/years-without-new-srp-version.png[]
Что тут в английской версии написать? "...  years without new SRP version"?

2021-09-22 23:21 UTC, d-r-q commented on azhidkov.pro/content/posts/21/06/210626-srp-interpretations.en.adoc
> +This was an excellent explanation of SRP history, all the way until Martin wrote his last post on SRP.
```suggestion
This was an excellent explanation of SRP evolution, all the way until Martin wrote his last post on SRP.
```
?

2021-09-22 23:21 UTC, d-r-q commented on azhidkov.pro/content/posts/21/06/210626-srp-interpretations.en.adoc
> +// декомпозиция упоминается в первый (и возможно последний) раз, надо упомянуть выше
Пусть будет разделение/separation

2021-09-22 23:21 UTC, d-r-q commented on azhidkov.pro/content/posts/21/06/210626-srp-interpretations.en.adoc
> +You can separate SQL and JSP and still use the same code in different functions, as well as break
Тут причинно-следственная связь "вы всё ещё можете использовать один и тот же код в разных функциях" -> "будете ломать функции одних пользователей при модификации функции других пользователей"

2021-09-22 23:21 UTC, d-r-q commented on azhidkov.pro/content/posts/21/06/210626-srp-interpretations.en.adoc
> +microservice, as well as have just one method for json parsing, business rules,  and SQL request execution.
А тут наоборот "вы можете разделить функции системы на микросервисы и при этом заталкать все "консёрны" в одну подпрограмму в коде"

2021-09-27 17:05 UTC, shamisem commented on azhidkov.pro/content/posts/21/06/210626-srp-interpretations.en.adoc
> +This was an excellent explanation of SRP history, all the way until Martin wrote his last post on SRP.
the way SRP evolved для фокуса на процессе?

2021-09-27 17:11 UTC, shamisem commented on azhidkov.pro/content/posts/21/06/210626-srp-interpretations.en.adoc
> +image::/posts/21/06/images/years-without-new-srp-version.png[]
years without new SRP formula

2021-09-29 23:35 UTC, d-r-q commented
Давайте следующий пост отдельным PR-ом

2021-10-07 00:21 UTC, closed without merging